/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const StressPrediction = IDL.Record({
  'method' : IDL.Text,
  'stressed' : IDL.Bool,
  'confidence' : IDL.Float64,
});

export const idlService = IDL.Service({
  'getStressDetectionMethods' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
  'processFacialAnalysisResult' : IDL.Func(
      [IDL.Bool, IDL.Float64],
      [StressPrediction],
      [],
    ),
  'processTextAnalysisResult' : IDL.Func(
      [IDL.Bool, IDL.Float64],
      [StressPrediction],
      [],
    ),
  'processVoiceAnalysisResult' : IDL.Func(
      [IDL.Bool, IDL.Float64],
      [StressPrediction],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const StressPrediction = IDL.Record({
    'method' : IDL.Text,
    'stressed' : IDL.Bool,
    'confidence' : IDL.Float64,
  });
  
  return IDL.Service({
    'getStressDetectionMethods' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
    'processFacialAnalysisResult' : IDL.Func(
        [IDL.Bool, IDL.Float64],
        [StressPrediction],
        [],
      ),
    'processTextAnalysisResult' : IDL.Func(
        [IDL.Bool, IDL.Float64],
        [StressPrediction],
        [],
      ),
    'processVoiceAnalysisResult' : IDL.Func(
        [IDL.Bool, IDL.Float64],
        [StressPrediction],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };